---
- hosts: db
  become: yes
  ignore_errors: false
  gather_facts: 0
  tasks:
     - name: install packages
       yum:
         name: "{{ item }}"
         state: present
#       with_items:
       loop:
        - curl
        - finger
        - wget
        - httpd
        - ntp  